# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 30

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      pre-commit:
        patterns:
          - "*"
    cooldown:
      default-days: 30
