default: true
no-duplicate-heading:
  # Check for duplicate headings only amongst sibling headings.  Allow duplicate
  # headings in separate sections, which is common in CHANGELOGs (e.g., Fixed,
  # Added, Changed).
  siblings_only: true
