# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.ci/ for CI configuration

ci:
  autofix_prs: false

default_language_version:
  python: python3.11
repos:
  - repo: local
    hooks:
      # Make sure the conda-lock.yml file is up to date if the conda environment
      # files have been changed.  We don't want to commit an outdated lock file.
      # Since `conda` is not installed on the pre-commit.ci, this will simply
      # fail the CI build if the lock file is outdated.
      - id: conda-lock
        name: update conda-lock.yml file
        language: system
        entry: make lock
        pass_filenames: false
        files: "^(environment.*.yml|bin/lock)$"
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        exclude: conda-lock.yml
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
        args: []
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
