algorithm_name: gedi-subset
algorithm_version: 0.14.0
algorithm_description: >-
  Subset GEDI L1B, L2A, L2B, L4A, or L4C granules within an area of interest (AOI).
keywords: OGC, GEDI
code_repository: https://github.com/MAAP-Project/gedi-subsetter.git
citation: https://zenodo.org/records/15284245
author: MAAP
contributor: MAAP
license: https://github.com/MAAP-Project/gedi-subsetter/blob/main/LICENSE
release_notes: None
docker_container_url: mas.maap-project.org/root/maap-workspaces/custom_images/maap_base:v5.0.0
build_command: gedi-subsetter/bin/build.sh
run_command: gedi-subsetter/bin/subset.sh
ram_min: 8 # mebibytes
cores_min: 2
outdir_max: 20 # mebibytes

inputs:
  - name: aoi
    label: URL of file describing Area of Interest (AOI)
    type: File
    doc: >-
      URL of a file representing the Area of Interest (e.g., GeoJSON file)

  - name: doi
    label: Collection Identifier
    type: string
    doc: >-
      Either the Digital Object Identifier (DOI) or the Concept ID of the
      GEDI collection to subset.  For convenience, one of these logical
      names may be specified instead: L1B, L2A, L2B, L4A, L4C.

  - name: columns
    label: Columns
    type: string
    doc: >-
      One or more column names, separated by commas, to include in the
      output file, each naming a variable (dataset) from the collection.

  - name: query
    label: Query Expression
    type: string
    doc: >-
      Boolean query expression for subsetting the rows of data.  If not
      provided, all rows are included.  For details on query syntax, see
      https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html.

  - name: lat
    label: Latitude Variable
    type: string
    default: lat_lowestmode
    doc: >-
      Name of the variable (dataset) containing latitude values.

  - name: lon
    label: Longitude Variable
    type: string
    default: lon_lowestmode
    doc: >-
      Name of the variable (dataset) containing longitude values.

  - name: temporal
    label: Temporal Range
    type: string
    # We are forced to supply a non-empty default due to MAAP Hub Job UI limitation.
    default: "2018-01-01T00:00:00Z/"
    doc: >-
      Temporal range to subset, formatted as an ISO 8601 Time Interval.
      For example, 2021-01-01T00:00:00Z/2021-12-31T23:59:59Z.  See
      https://en.wikipedia.org/wiki/ISO_8601#Time_intervals.  If not provided,
      the entire temporal range of the GEDI collection is used.

  - name: beams
    label: Beams
    type: string
    default: all
    doc: >-
      Which beams to include: all, coverage, power, or a comma-separated
      list of specific beam names, with or without the BEAM prefix (e.g.,
      BEAM0000,BEAM0001 or 0000,0001).

  - name: limit
    label: Limit
    type: int
    default: 100000
    doc: >-
      Maximum number of GEDI granules to subset, regardless of the number
      of granules within the spatio-temporal range.

  - name: output
    label: Output Filename
    type: string
    default: gedi-subset.parquet
    doc: >-
      Name of the output file produced by the algorithm.  Defaults to using
      the AOI filename (without the extension) with the suffix `_subset`
      and the extension `.gpkg`, resulting in a GeoPackage file format.

      For example, if the AOI were `https://host/path/to/my_aoi.geojson`,
      the default output filename would be `my_aoi_subset.gpkg`.

      When a filename is supplied, it must include a file extension in order
      to infer the output format.  Supported formats inferred from file
      extensions are as follows:

        - FlatGeobuf: `.fgb`
        - GPKG (GeoPackage): `.gpkg`
        - (Geo)Parquet: `.parquet`

      For example, if you prefer a Parquet file as output, you would specify
      a value such as `my_aoi.parquet` (where `my_aoi` can be whatever name
      you prefer).

  - name: tolerated-failure-percentage
    label: Tolerated Failure Percentage
    type: int
    default: 0
    doc: >-
      Integral percentage of individual granule subset failures tolerated
      before causing job failure.  For example, a value of 0 indicates that
      no individual granule failures are tolerated.  Thus, if an error is
      encountered during subsetting of any individual granule, the entire
      job will fail.

      Conversely, a value of 100 indicates that even if an error is
      encountered for every granule, the job will still succeed, resulting
      in an empty output file.

  - name: fsspec-kwargs
    label: "[Advanced] Keyword Arguments for fsspec configuration"
    type: string
    default: "{}"
    doc: >-
      JSON object representing keyword arguments to pass to the
      fsspec.core.url_to_fs function when reading granule data files.  See
      https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.core.url_to_fs.

  - name: processes
    label: "[Advanced] Number of Processes"
    type: int
    default: 0
    doc: >-
      Number of processes to use for parallel processing.  If not provided, or
      a value less than 1 is provided, defaults to the number of CPUs available
      on the provisioned instance.

outputs:
  - name: output
    type: Directory
