description: Subset GEDI L1B, L2A, L2B, or L4A granules within an area of interest (AOI)
algo_name: gedi-subset
version: 0.6.2
environment: ubuntu
repository_url: https://repo.ops.maap-project.org/data-team/gedi-subsetter.git
docker_url: mas.dit.maap-project.org/root/maap-workspaces/base_images/r:dit
queue: maap-dps-worker-32gb
build_command: gedi-subsetter/bin/build-dps.sh
run_command: gedi-subsetter/bin/subset.sh
disk_space: 20GB
inputs:
  - name: aoi
    download: True
  - name: doi
    download: False
  - name: temporal
    download: False
  - name: lat
    download: False
  - name: lon
    download: False
  - name: beams
    download: False
  - name: columns
    download: False
  - name: query
    download: False
  - name: limit
    download: False
  - name: output
    download: False
  - name: scalene_args
    download: False
