name: gedi_subset
channels:
  - conda-forge
  - defaults
# Non-standard, but recognized by conda-lock
category: dev
dependencies:
  - backoff~=2.2
  - black~=24.0
  # boto*-stubs constraints should align with boto3 constraint in environment.yml
  - boto3-stubs~=1.33
  - boto3-stubs-essential~=1.33
  - botocore-stubs~=1.33
  - contextily~=1.3
  - flake8~=7.0
  - ipykernel~=6.23
  - isort~=5.13
  - moto~=4.1
  - mypy~=1.2
  # pandas-stubs constraint should align with pandas constraint in environment.yml
  - pandas-stubs~=2.0
  - pre-commit~=3.3
  - pytest~=7.3
  - pytest-recording~=0.13
  - vcrpy~=6.0
  - shellcheck~=0.9
  - types-requests~=2.30
platforms:
  - linux-64
  - osx-64
  - osx-arm64
