name: gedi_subset
channels:
  - conda-forge
  - defaults
# Non-standard, but recognized by conda-lock
category: dev
dependencies:
  - backoff
  - boto3-stubs
  - boto3-stubs-essential
  - botocore-stubs
  - contextily
  - ipykernel
  - moto
  - mypy
  - pandas-stubs
  - pre-commit
  - pytest
  - pytest-recording
  - ruff
  - shellcheck
  - types-requests
  - vcrpy
platforms:
  - linux-64
  - osx-64
  - osx-arm64
