name: gedi_subset
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - pip:
    - git+https://github.com/MAAP-Project/maap-py.git@d0f34e3440bf1121882892a5fe0b20484b413d43#egg=maappy
