name: gedi_subset
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.4
  - boto3==1.24.1
  - cachetools==5.0.0
  - returns==0.19.0
  - typer==0.4.1
  - geopandas==0.10.2
  - h5py==3.6.0
  - pyarrow==8.0.0
  - shapely==1.8.2
  - pip
