name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v5

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0

      - name: Run unit tests
        run: pixi run test

  type-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v5

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0

      - name: Run static type analysis
        run: pixi run mypy

  validate-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v5

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0

      - name: Validate "prod" installation
        run: bin/build.sh
