# Input params for OGC application package generator
algorithm_description: Subset GEDI L1B, L2A, L2B, L4A, or L4C granules within an area of interest (AOI)
algorithm_name: gedi-subset
algorithm_version: mlucas/ogc
keywords: OGC, GEDI
code_repository: https://github.com/MAAP-Project/gedi-subsetter.git
citation: https://zenodo.org/records/15284245
author: MAAP
contributor: MAAP
license: https://github.com/MAAP-Project/gedi-subsetter/blob/main/LICENSE
release_notes: None
run_command: /app/gedi-subsetter/bin/subset.sh
ram_min: 5 # mebibytes
cores_min: 1
outdir_max: 20 # mebibytes

inputs:
  - name: aoi
    doc: URL to a GeoJSON file representing your area of interest. This may contain multiple geometries, all of which will be used.
    label: Area of Interest
    type: string
  - name: doi
    doc: Digital Object Identifier (DOI) or Concept ID of the GEDI collection to subset, or a logical name representing such an ID.
    label: Digital Object Identifier
    type: string
  - name: lat
    doc: Name of the dataset containing latitude values
    label: latitude
    type: string
  - name: lon
    doc: Name of the dataset containing longitude values
    label: longitude
    type: string
  - name: columns
    doc: One or more column names, separated by commas, to include in the output file. These names correspond to the datasets (which might also be referred to as variables or layers in the DOI documentation) within the data files, and vary from collection to collection.
    label: columns
    type: string
    

outputs:
  - name: out
    type: Directory
